# Лабораторная работа №5. Разработка единого подхода к предварительной обработки данных.

Выполнил: Мелтонян Одиссей Гарикович

Группа: пиж-б-о-22-1

__Цель лабораторной работы:__ изучение теоретических принципов и инструментальных редств для построения пайплайна для предварительной обработки данных.


## Ход работы

1. Реализлвана первичная обработка данных загруженного набора. Выполнен полный спектр операций для загруженного набора данны: загрузка, визуализация, обработка пропущенных значений, обработка категориальных данных и разделение выборки на тестовую и тренировочную.

In [ ]:
# Загрузка данных
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

dataset = pd.read_csv('data.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [ ]:
# Визуализация данных
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 3].values
print('Матрица признаков:\n', x)
print()
print('Зависимая переменная:\n', y)

Матрица признаков:
 [['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]

Зависимая переменная:
 ['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
# Обработка категориальных данных
from sklearn.preprocessing import LabelEncoder

labelencoder_y = LabelEncoder()
y_transformed = labelencoder_y.fit_transform(y)
print(y_transformed)

[0 1 0 0 1 1 0 1 0 1]


In [ ]:
# Обработка категориальных данных и заполнение пропусков
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer

transformers = [
    ('onehot', OneHotEncoder(), [0]),
    ('imp', SimpleImputer(), [1, 2])
]
ct = ColumnTransformer(transformers)
x_transformed = ct.fit_transform(x)
print(x_transformed.shape)
x_transformed


(10, 5)


array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 3.00000000e+01,
        5.40000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e+01,
        8.30000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04]])

In [ ]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_transformed, y_transformed, test_size=0.2, random_state=42)
print('Тренировочкая выборка:', x_train, y_train, sep='\n')
print('Тестовая выборка:', x_test, y_test, sep='\n')

Тренировочкая выборка:
[[1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]]
[1 0 1 0 1 1 0 0]
Тестовая выборка:
[[0.0e+00 1.0e+00 0.0e+00 5.0e+01 8.3e+04]
 [0.0e+00 0.0e+00 1.0e+00 2.7e+01 4.8e+04]]
[0 1]


In [ ]:
# Можно преобразовать полученный многомерный массив обратно в Dataframe
x_data = pd.DataFrame(
    x_test,
    columns=['C1', 'C2', 'C3', 'Age', 'Salary'])
y_date = pd.DataFrame(
    y_test,
    columns=['Purchased']
)
print(x_data, y_date, sep='\n')

    C1   C2   C3   Age   Salary
0  0.0  1.0  0.0  50.0  83000.0
1  0.0  0.0  1.0  27.0  48000.0
   Purchased
0          0
1          1


## Контрольные вопросы

1. **Какая библиотека python предназначена для управления наборами данных: numpy, pandas, sklearn, opencv, matplotlib?**

   Библиотека **pandas** предназначена для управления наборами данных. Она предоставляет структуры данных и функции для работы с таблицами и временными рядами, что делает её удобной для анализа данных.

2. **Какая стратегия является нежелательной при обработке пропусков в данных?**

   б **удаление строк, содержащих пропуски в данных**;
   
   Удаление строк с пропусками может привести к значительным потерям данных, особенно если пропусков много. Это может исказить результаты анализа и уменьшить статистическую мощность.

3. **Обоснуйте ответ на следующую проблему предварительной обработки данных: имеется независимая категориальная переменная y, которая представляет собой категориальный признак, определённый на домене {C#, Java, Python, R}. Нужно ли применять к данному целевому признаку OneHotEncoder?**

   Если переменная **y** является целевым признаком (то есть, это переменная, которую мы пытаемся предсказать), то к ней **не нужно** применять OneHotEncoder. В таких случаях, когда целевая переменная категориальная, её обычно кодируют с помощью LabelEncoder или используют её как есть в виде категорий. OneHotEncoder применяется к категориальным признакам, которые используются в качестве входных данных для модели (то есть к независимым переменным), чтобы предотвратить порядок категорий в модельных вычислениях.

4. **Поясните принцип разбиения набора данных на обучающую и тестовую выборку. Какое соотношение «тестовая:обучающая» наиболее оптимально: 20:80, 50:50, 25:75, 5:95, 40:30?**

   Принцип разбиения набора данных на обучающую и тестовую выборку заключается в том, чтобы оценить производительность модели на новых, невидимых данных. Обучающая выборка используется для построения модели, а тестовая выборка – для её оценки.
   
   Наиболее оптимальное соотношение **20:80**. Это позволяет достаточно данных использовать для обучения модели, сохраняя при этом достаточно данных для её тестирования. В некоторых случаях может использоваться соотношение 25:75 или другие варианты в зависимости от конкретной задачи и объёма данных.

5. **Какой код лучше использовать при загрузке данных из csv-файла?**

   а **dataset = read_csv(“data.csv”)**
   
   В Python для загрузки данных из CSV-файлов обычно используется функция `read_csv` из библиотеки pandas. Это стандартный и наиболее распространённый способ.

```python
import pandas as pd
dataset = pd.read_csv("data.csv")
```

Ответы на все вопросы предоставлены с учётом лучших практик и широко используемых методов в области анализа данных и машинного обучения.